import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/components/AuthProvider";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet" />
        <style>{`
          body {
            font-family: 'Montserrat', Arial, Helvetica, sans-serif;
          }
        `}</style>
      </head>
      <body>
        <NavBar />
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
